reorg

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,7 +1,7 @@
 #! /bin/bash
 # Link everthing in '$PWD' to a dir in '~/$PWD'
 #
-# Put a copy of his in any directory that should have it's
+# Put a COPY (not link) of his in any directory that should have it's
 # file linked into root.
 
 # Any files listed (one per line) in .install.ignore will be ignored
@@ -14,7 +14,18 @@ cd ${WHERE_AM_I}
 # Extract the directory name of this file
 BASEDIR=`basename $WHERE_AM_I`
 
+# find link2home.sh script
+if [ -e ${HOME}/bin/link2home.sh ]; then
+   LINK2HOME="${HOME}/bin/link2home.sh"
+elif [ -e ${WHERE_AM_I}/link2home.sh ]; then
+   LINK2HOME="${WHERE_AM_I}/link2home.sh"
+else
+   echo "Can't find link2home.sh"
+   exit 1
+fi
+
+
 echo Linking evertying in "${WHERE_AM_I}"  into "~/""${BASEDIR}"
-~/bin/link2home.sh -v -d
+${LINK2HOME} -v -d -r --home
 
 # any directory specific post-processing (permissions, etc) goes here.
